FROM ubuntu:18.04 as base

WORKDIR /build

RUN mkdir ~/certs

RUN apt-get update && apt-get install -y curl dos2unix python python-pip git lsb

RUN pip install awscli

ADD ./client_entrypoint.sh .
RUN dos2unix ./client_entrypoint.sh && chmod u+x ./client_entrypoint.sh

ENTRYPOINT [ "./client_entrypoint.sh" ]
