FROM ubuntu:18.04 as base

WORKDIR /build

RUN apt-get update && apt-get install -y curl dos2unix python python-openssl python-pip git

RUN mkdir ~/keys

#Install Certificate Generator
RUN git clone https://github.com/Cherie-Chen/SSLGeneration.git &&\
    pip install pyopenssl

RUN mkdir /client_certs

#Install Database
RUN mkdir -p /opt/Thinkbox/DeadlineDatabase10/mongo/data &&\
    mkdir -p /opt/Thinkbox/DeadlineDatabase10/mongo/application &&\
    mkdir -p /opt/Thinkbox/DeadlineDatabase10/mongo/data/logs

COPY ./database_config/config.conf /opt/Thinkbox/DeadlineDatabase10/mongo/data/
RUN curl https://downloads.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-5.0.26.tgz -o mongodb-linux-x86_64-ubuntu1804-5.0.26.tgz 
RUN tar -xvf mongodb-linux-x86_64-ubuntu1804-5.0.26.tgz
RUN mv mongodb-linux-x86_64-ubuntu1804-5.0.26/bin /opt/Thinkbox/DeadlineDatabase10/mongo/application/
RUN rm mongodb-linux-x86_64-ubuntu1804-5.0.26.tgz && rm -rf mongodb-linux-x86_64-ubuntu1804-5.0.26

ADD ./database_entrypoint.sh .
RUN dos2unix ./database_entrypoint.sh && chmod u+x ./database_entrypoint.sh

ENTRYPOINT [ "./database_entrypoint.sh" ]
