version: '3.8'
services:

  deadline-db:
    restart: unless-stopped
    container_name: deadline-db
    image: ghcr.io/emberlightvfx/deadline_docker/database:1.0.0
    env_file:
      - .env
    volumes:
      - certs:/client_certs
      - repo:/repo
      - db_data:/opt/Thinkbox/DeadlineDatabase10/mongo/data
      - data:/opt/data
      - keys:/root/keys
      - unpacked_installers:/unpacked_installers
    command: repository
    ports:
      - 27100:27100

  deadline-rcs:
    depends_on:
      - deadline-db
    restart: unless-stopped
    container_name: deadline-rcs
    hostname: deadline-rcs.$ROOT_DOMAIN
    image: ghcr.io/emberlightvfx/deadline_docker/client:1.0.0
    command: rcs
    env_file:
      - .env
    volumes:
      - certs:/client_certs
      - server_certs:/server_certs
      - repo:/repo
      - installers:/installers
      - unpacked_installers:/unpacked_installers
    ports:
      - 4433:4433
      - 8888:8888

  filebrowser:
    image: filebrowser/filebrowser
    container_name: deadline-filebrowser
    restart: unless-stopped
    volumes:
      - repo:/srv/repo
      - certs:/srv/certs
      - installers:/srv/installers
    ports:
      - 8080:80

volumes:
  db_data:
  certs:
  server_certs:
  repo:
  data:
  keys:
  installers:
  unpacked_installers:


