
name: Docker Build and Publish

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  repository_dispatch:
    types: [docker-publish]
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Version"
        required: true
        default: "1.0.0"
      LATEST:
        description: "Latest"
        required: true
        default: true
        type: boolean

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Set Environment Variable
        run: |
          # Version
          if [ -n "${{ github.event.client_payload.VERSION }}" ]; then
            VERSION=${{ github.event.client_payload.VERSION }}
          else
            VERSION=${{ inputs.VERSION }}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # Latest tag
          if [ -z "${{ inputs.LATEST }}" ] || [ "${{ inputs.LATEST }}" == "true" ]; then
            LATEST="true"
          else
            LATEST="false"
          fi
          echo "LATEST=$LATEST" >> $GITHUB_ENV

      - name: Version and Latest tag
        run: |
          echo "The VERSION is ${{ env.VERSION }}"
          echo "Latest tag is set to  ${{ env.LATEST }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: latest=${{ env.LATEST }}
          tags: type=raw,value=${{ env.VERSION }}

      - name: Meta version
        run: echo "The Meta is ${{ steps.meta.outputs.tags }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VERSION=${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max